GET http://localhost:3000/products/ HTTP/1.1

###

GET http://localhost:3000/orders/ HTTP/1.1

###

GET http://localhost:3000/users/ HTTP/1.1

###

POST http://localhost:/3000/user/signup HTTP/1.1
content-type: application/json
{
    "email": "johndoe@mail.com",
    "password": "123456"
}